// Command lutgen derives the pure-op lookup tables from pow.go.
//
// An op case is "pure" when its whole body is a single `for i := pos1; i < pos2; i++`
// loop that only ever assigns to step_3[i] from step_3[i]. Such a case is a function
// of one byte, so it collapses to a 256-entry table. Cases that read step_3[pos1] or
// step_3[pos2], touch lhash/rc4s, or carry a prologue (253, 254/255) are not pure and
// are left to the switch.
//
// The bodies are extracted from pow.go rather than hand-copied: a single wrong table
// byte yields a wrong hash and invalid shares, and this keeps the tables from ever
// drifting away from the reference switch.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"strconv"
	"strings"
)

const srcFile = "pow.go"

var outFile = flag.String("o", "pureop_gen.go", "output path")

// forbidden names must not appear in a pure body. step_3 is checked separately:
// every occurrence has to be the exact index expression step_3[i].
var forbidden = []string{
	"lhash", "prev_lhash", "tries", "rc4s", "counter",
	"highwayhash", "xxhash", "fnv1a", "NewCipher",
}

func main() {
	flag.Parse()
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "lutgen:", err)
		os.Exit(1)
	}
}

func run() error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, srcFile, nil, 0)
	if err != nil {
		return err
	}

	sw := findOpSwitch(f)
	if sw == nil {
		return fmt.Errorf("could not find `switch op` in %s", srcFile)
	}

	type pureCase struct {
		op   int
		body string
	}
	var pure []pureCase

	for _, stmt := range sw.Body.List {
		cc, ok := stmt.(*ast.CaseClause)
		if !ok || len(cc.List) != 1 {
			// default:, or a multi-value case such as `case 254, 255:`.
			continue
		}
		lit, ok := cc.List[0].(*ast.BasicLit)
		if !ok || lit.Kind != token.INT {
			continue
		}
		op, err := strconv.Atoi(lit.Value)
		if err != nil || op < 0 || op > 255 {
			continue
		}
		body, ok := pureBody(fset, cc)
		if !ok {
			continue
		}
		pure = append(pure, pureCase{op: op, body: body})
	}

	if len(pure) == 0 {
		return fmt.Errorf("no pure ops found; the shape of %s must have changed", srcFile)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by lutgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package astrobwt\n\n")
	fmt.Fprintf(&buf, "import \"math/bits\"\n\n")
	fmt.Fprintf(&buf, "// pureOpCount is the number of ops that are a function of a single byte.\n")
	fmt.Fprintf(&buf, "const pureOpCount = %d\n\n", len(pure))

	fmt.Fprintf(&buf, "// pureOpSet reports which ops pureOp can evaluate.\n")
	fmt.Fprintf(&buf, "var pureOpSet = [256]bool{\n")
	for _, pc := range pure {
		fmt.Fprintf(&buf, "\t%d: true,\n", pc.op)
	}
	fmt.Fprintf(&buf, "}\n\n")

	fmt.Fprintf(&buf, "func isPureOp(op byte) bool { return pureOpSet[op] }\n\n")
	fmt.Fprintf(&buf, "// pureOp applies op's byte transform to x. Only valid when isPureOp(op).\n")
	fmt.Fprintf(&buf, "// Bodies are lifted verbatim from the switch in %s with step_3[i] renamed to x.\n", srcFile)
	fmt.Fprintf(&buf, "func pureOp(op, x byte) byte {\n\tswitch op {\n")
	for _, pc := range pure {
		fmt.Fprintf(&buf, "\tcase %d:\n%s", pc.op, pc.body)
	}
	fmt.Fprintf(&buf, "\t}\n\treturn x\n}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w", err)
	}
	return os.WriteFile(*outFile, src, 0o644)
}

// findOpSwitch returns the `switch op { ... }` statement.
func findOpSwitch(f *ast.File) *ast.SwitchStmt {
	var found *ast.SwitchStmt
	ast.Inspect(f, func(n ast.Node) bool {
		if found != nil {
			return false
		}
		sw, ok := n.(*ast.SwitchStmt)
		if !ok || sw.Init != nil {
			return true
		}
		if id, ok := sw.Tag.(*ast.Ident); ok && id.Name == "op" {
			found = sw
			return false
		}
		return true
	})
	return found
}

// pureBody validates that cc is a pure per-byte case and returns its statements
// rewritten over x. The second result is false when the case is not pure.
func pureBody(fset *token.FileSet, cc *ast.CaseClause) (string, bool) {
	if len(cc.Body) != 1 {
		return "", false // a prologue (rc4 rekey) or extra trailing work
	}
	loop, ok := cc.Body[0].(*ast.ForStmt)
	if !ok || !isCanonicalLoop(loop) {
		return "", false
	}

	var out strings.Builder
	for _, stmt := range loop.Body.List {
		as, ok := stmt.(*ast.AssignStmt)
		if !ok || len(as.Lhs) != 1 || len(as.Rhs) != 1 {
			return "", false
		}
		if !isStep3I(as.Lhs[0]) {
			return "", false
		}
		text, ok := render(fset, stmt)
		if !ok {
			return "", false
		}
		out.WriteString("\t\t")
		out.WriteString(text)
		out.WriteString("\n")
	}
	if out.Len() == 0 {
		return "", false
	}
	return out.String(), true
}

// isCanonicalLoop matches exactly `for i := pos1; i < pos2; i++`.
func isCanonicalLoop(loop *ast.ForStmt) bool {
	init, ok := loop.Init.(*ast.AssignStmt)
	if !ok || init.Tok != token.DEFINE || len(init.Lhs) != 1 || len(init.Rhs) != 1 {
		return false
	}
	if !isIdent(init.Lhs[0], "i") || !isIdent(init.Rhs[0], "pos1") {
		return false
	}
	cond, ok := loop.Cond.(*ast.BinaryExpr)
	if !ok || cond.Op != token.LSS || !isIdent(cond.X, "i") || !isIdent(cond.Y, "pos2") {
		return false
	}
	post, ok := loop.Post.(*ast.IncDecStmt)
	return ok && post.Tok == token.INC && isIdent(post.X, "i")
}

// render prints stmt and rewrites step_3[i] to x, refusing anything that still
// mentions step_3 or any hash state afterwards.
func render(fset *token.FileSet, stmt ast.Stmt) (string, bool) {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, stmt); err != nil {
		return "", false
	}
	text := buf.String()
	text = strings.ReplaceAll(text, "step_3[i]", "x")
	// Any surviving step_3 means a cross-byte read such as step_3[pos2].
	if strings.Contains(text, "step_3") {
		return "", false
	}
	for _, bad := range forbidden {
		if strings.Contains(text, bad) {
			return "", false
		}
	}
	return text, true
}

func isStep3I(e ast.Expr) bool {
	ix, ok := e.(*ast.IndexExpr)
	return ok && isIdent(ix.X, "step_3") && isIdent(ix.Index, "i")
}

func isIdent(e ast.Expr, name string) bool {
	id, ok := e.(*ast.Ident)
	return ok && id.Name == name
}
